#pragma once

namespace gasp::blaise
{

enum class blaise_token_type : unsigned char
{
   UNKNOWN = 0,

   // KEYWORDS
   PROGRAM = 1,
   MODULE,
   USE,
   BEGIN,
   END,
   VAR,
   CONST,
   LOGICAL_AND,
   LOGICAL_OR,
   LOGICAL_NOT,
   DECLARE,
   FUNCTION,
   PROCEDURE,
   NATIVE,
   CAST,
   IF,
   THEN,
   ELSE,
   DO,
   WHILE,
   REPEAT,
   UNTIL,
   FOR,
   FROM,
   TO,
   STEP,
   NEW,
   DELETE,

   // TYPES
   TYPE_INTEGER,
   TYPE_CHAR,
   TYPE_FLOAT,
   TYPE_DOUBLE,
   TYPE_BOOLEAN,
   TYPE_ARRAY,
   TYPE_LONG,
   TYPE_SHORT,
   TYPE_BYTE,

   // PUNCTUATION
   ASSIGNMENT,
   SEMICOLON,
   PERIOD,
   COLON,
   COMMA,
   LEFT_PARENTHESES, RIGHT_PARENTHESES,
   LEFT_BRACKET, RIGHT_BRACKET,
   GREAT_THAN, LESS_THAN, GREAT_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO,
   EQUAL_TO, NOT_EQUAL_TO,
   PLUS, MINUS,
   MULTIPLY, DIVIDE, REMAINDER,
  
   // OTHERS
   IDENTIFIER,
   LITERAL_INTEGER,
   LITERAL_FLOAT,
   LITERAL_DOUBLE,
   LITERAL_BYTE,
   LITERAL_SHORT,
   LITERAL_LONG,
   LITERAL_INTEGER_BINARY,
   LITERAL_INTEGER_OCTAL,
   LITERAL_INTEGER_HEX,
   LITERAL_STRING,
   LITERAL_CHAR,
   LITERAL_BOOLEAN,
};
}